sudo: required
dist: trusty
language: shell
before_install:
  - sudo apt-add-repository 'deb http://ppa.launchpad.net/anatol/tup/ubuntu precise main'
  - sudo apt-get update 
  - sudo apt-get install --allow-unauthenticated -y -qq pkg-config fuse latexmk texlive-full tup wget python3 python3-pip git biber
  - wget https://github.com/jgm/pandoc/releases/download/2.0.1.1/pandoc-2.0.1.1-1-amd64.deb -O pand2.deb
  - sudo dpkg -i pand2.deb
  - bash scripts/libsassUbuntu.sh
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add surge
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

script:
  - tup

deploy:
  provider: surge
  project: ./docs/
  domain: zenyoda.surge.sh