sudo: required
dist: trusty
language: shell
before_install:
  - sudo apt-add-repository 'deb http://ppa.launchpad.net/anatol/tup/ubuntu precise main'
  - sudo apt-get install python-software-properties
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update 
  - sudo apt-get install --allow-unauthenticated -y -qq xzdec nodejs yarn pkg-config fuse tup wget python3 python3-pip git
  - wget https://github.com/jgm/pandoc/releases/download/2.0.1.1/pandoc-2.0.1.1-1-amd64.deb -O pand2.deb
  - sudo dpkg -i pand2.deb
  - bash scripts/beamerSetup.sh
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

install:
  - sudo yarn global add shx surge node-sass
  - sudo pip3 install panflute
  - sudo pip install panflute

script:
  - tup

deploy:
  provider: pages
  local_dir: ./docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  provider: surge
  project: ./docs/
  domain: zenyoda.surge.sh